POST http://localhost:5287/albuns/
Content-Type: application/json

{
    "Nome": "The Perfect Velvet",
    "Artistas": "Red Velvet",
    "Generos": "Kpop, R&B",
    "Colaboradores": "-",
    "DataLancamento": "29-01-2018",
    "NumeroFaixas": 12,
    "Duracao": "41:36",
    "Gravadora": "SM Entertainment",
    "Formato": "Álbum"
}

###

DELETE http://localhost:5287/albuns/1
