GET http://localhost:5287/albuns/

###

GET http://localhost:5287/albuns/4

###

POST http://localhost:5287/albuns/
Content-Type: application/json

{
    "Nome": "qualquer album",
    "Artistas": "aaaaaaa",
    "Generos": "bbbbbb",
    "Colaboradores": "3",
    "DataLancamento": "29-01-2018",
    "NumeroFaixas": 10,
    "Duracao": "41:36",
    "Gravadora": "cccccc",
    "Formato": "Álbum"
}

###

PUT http://localhost:5287/albuns/11
Content-Type: application/json

{
    "Nome": "qualquer albumm",
    "Artistas": "aaa",
    "Generos": "bbb",
    "Colaboradores": "3",
    "DataLancamento": "29-01-2018",
    "NumeroFaixas": 5,
    "Duracao": "40:00",
    "Gravadora": "ccc",
    "Formato": "Álbum"
}

### 

PATCH http://localhost:5287/albuns/11
Content-Type: application/json

{
    "Generos": "ddd",
    "DataLancamento": "30-02-2018",
    "NumeroFaixas": 15,
    "Gravadora": "eee"
}

###
DELETE http://localhost:5287/albuns/11
