// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PantanalVaultAPI;

#nullable disable

namespace PantanalVaultAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251101173523_remove_propriedade_colaboradores")]
    partial class removepropriedadecolaboradores
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("PantanalVaultAPI.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artistas")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataLancamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Duracao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Formato")
                        .HasColumnType("TEXT");

                    b.Property<string>("Generos")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gravadora")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroFaixas")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Albuns");
                });
#pragma warning restore 612, 618
        }
    }
}
