// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PantanalVaultAPI;

#nullable disable

namespace PantanalVaultAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("PantanalVaultAPI.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artistas")
                        .HasColumnType("TEXT");

                    b.Property<string>("Colaboradores")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataLancamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Duracao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Formato")
                        .HasColumnType("TEXT");

                    b.Property<string>("Generos")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gravadora")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroFaixas")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Albuns");
                });
#pragma warning restore 612, 618
        }
    }
}
